### ISSUE TITLE
关于全字庫音韻讀音版-2020年末.txt的问题

### ISSUE THREAD

**Issue by wwzrh** [ShikiSuen/vchewing-lingual-data#1]
@ShikiSuen
请问：1.这个libvchewing-data/valueadd/phonetic-data/references/全字庫音韻讀音版-2020年末.txt
是你整理出来的，还是https://data.gov.tw/ (打不开)或http://www.cns11643.gov.tw/ (打不开)自有的？

2.这跟https://github.com/cjkvi/cjkvi-data/blob/master/cns2py.txt 的字码和读音有什么不同（更新）？

3.cns11643有几个版本？

**Comment by ShikiSuen** [comment]
我這邊威注音 macOS 在做新功能，結果有點故障了，暫時用雅虎注音打繁出簡，有錯字請見諒。

一、那兩個網站點不開很正常。因為現在咱們大陸這邊不再講一中各表的原因，所以右岸的這些公務機關的網站往往需要科學的上網手段才能正常瀏覽。

二、您給的 CNS 轉屁眼的檔案我沒見到過。我拿到的是一整套資料包，裡面有讀音與 CNS 編碼序號的對應表、以及 CNS 編碼與萬國碼碼序的對應表。我用 Excel & sed 等工具將兩張表對在一起，再用 LibreOffice 將 Unicode 碼序轉成漢字。Excel 對最新版的萬國碼的漢字的支援有問題，在跑 LEN 函數時會將單個字認成兩個字，唯一優勢就是在 macOS 系統下比 LibreOffice 操作反應快得多，所以不要只用 Excel。

三、我不清楚 CNS 有幾個版本，我用的是 2020 年底更新的版本，文字數量有點多得嚇人。

**Comment by ShikiSuen** [comment]
前篇回覆砍掉重新回答好了。

一、那两个网站点不开很正常，需要科学的上网手段才能正常浏览。

二、您给的 CNS 转屁眼的档案我没见到过。我拿到的是一整套资料包，里面有读音与 CNS 编码序号的对应表、以及 CNS 编码与万国码码序的对应表。我用 Excel & sed 等工具将两张表对在一起，再用 LibreOffice 将 Unicode 码序转成汉字。Excel 对最新版的万国码的汉字的支援有问题，在跑 LEN 函数时会将单个字认成两个字，唯一优势就是在 macOS 系统下比 LibreOffice 操作反应快得多，所以不要只用 Excel。

三、我不清楚 CNS 有几个版本，我用的是 2020 年底更新的版本，文字数量有点多得吓人。然而其中的读音必然没有收录大陆这边的审音（质 zhi4）与习惯读音（质 zhi3）。

**Comment by wwzrh** [comment]
其实使用https://www.unicode.org/Public/14.0.0/ucd/Unihan.zip 中汉字读音Unihan_Readings（kMandarin、kTGHZ2013、kXHC、kHanyuPinyin)已足够了。

**Comment by ShikiSuen** [comment]
我要想做全 Unicode 汉字输入的话，CNS11643 的音韵库是目前能用的最大的库。
其实通用规范汉字表的音韵我也有收就是了。

然而目前 macOS 版威注音尚未实质引入 CNS11643 的支援，只是在偏好设定面板内留了一个排版痕迹而已。
回头有机会我再想想怎么将这个功能弄进去。

![image](https://user-images.githubusercontent.com/3164826/150167163-4b38293e-9eef-4f56-8758-c7058d52fa26.png)

**Comment by ShikiSuen** [comment]
已引入 CNS11643 支援。
